# daemon-proxy配置文件
# 用于Dockerfile.daemon版本

server:
  host: "0.0.0.0"
  port: 8080

daemon:
  mode: "docker"
  host: "localhost"
  port: 2080
  path: "/usr/local/bin/daytona"
  container_name: "my-sandbox"
  startup_timeout: 30
  binary_source_path: "/app/daemon-proxy/daytona-daemon-static"
  injection_mode: "volume"
  injection_method: "copy"  # 生产环境默认使用拷贝方式

security:
  enabled: false
  api_key: "your-secret-key"

logging:
  level: "INFO"
  file: "logs/daemon-proxy.log"
  max_size: 10485760
  backup_count: 5

proxy:
  timeout: 30
  max_connections: 100
  keep_alive: true

preview:
  enabled: true
  default_expiry: 3600
  max_expiry: 86400
  cleanup_interval: 300
