version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - suna-network

networks:
  suna-network:
    driver: bridge