version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # 挂载Docker socket以访问Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
      # 挂载host上的daemon二进制文件到backend容器（只读）
      - /opt/suna/daemon-proxy/daytona-daemon-static:/app/daemon-proxy/daytona-daemon-static:ro
    environment:
      # Daemon二进制文件路径（容器内路径）
      - DAEMON_BINARY_PATH=/app/daemon-proxy/daytona-daemon-static
      # Host上的daemon二进制文件路径
      - HOST_DAEMON_BINARY_PATH=/opt/suna/daemon-proxy/daytona-daemon-static
      # 其他环境变量
      - PYTHONPATH=/app
      - LOG_LEVEL=info
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - suna-network
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  suna-network:
    driver: bridge
